# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, run tests across different versions of node, publish the package to npm registry, and create a new tag on every minor and major release
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI with Publish to NPM and Tagging

on:
  push:
    branches: ['master', 'development']
  pull_request:
    branches: ['master', 'development']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: install yarn globally
        run: npm install -g yarn
      - name: yarn install
        run: yarn
      - name: Run security check
        run: yarn audit-security
      - name: yarn lint
        run: yarn lint
      - name: yarn test
        run: yarn test
      - name: yarn build
        run: yarn build
      - name: Publish to NPM
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
        run: |
          npm publish --access public
      - name: Create Release Tag
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
