name: Node.js CI which runs lint, audit security vulnerability and available test cases.

on:
  push:
    branches: ['master', 'development']
  pull_request:
    branches: ['master', 'development']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: install yarn globally
        run: npm install -g yarn
      - name: yarn install
        run: yarn
      - name: Run security check
        run: yarn audit-security
      - name: yarn lint
        run: yarn lint
      - name: yarn test
        run: yarn test
      - name: yarn build
        run: yarn build
